sudo: false
language: node_js
node_js:
  - v8
  - v6
  - v4

install:
  - npm install -g codecov
  - npm install

before_script:
  - npm run eslint

script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l
  - codecov
