sudo: false
language: node_js
node_js:
  - "8"
  - "6"
  - "4"

install:
  - npm install -g codecov
  - npm install

before_script:
  - npm run eslint

script:
  - istanbul cover ./node_modules/lab/bin/lab --report lcovonly  -- -l
  - codecov
